name = "WRDS"
uuid = "01be1aad-4938-46f0-adad-3b8614061b76"
authors = ["Vadim Elenev <47358678+elenev@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
